In [4]:
import numpy as np
import pickle
from openeye import oechem
import copy
import mdtraj as md
import os

# Get the water indices (to be turned into ion) for complex

In [70]:
with open("/data/chodera/zhangi/perses_benchmark/neq/15/104/104_complex.pickle", "rb") as f:
    htf = pickle.load(f)

In [71]:
# Read in lambda = 0 cache
with open(os.path.join("/data/chodera/zhangi/perses_benchmark/neq/15/104/", f"104_complex_asp_1ns_snapshots.npy"), 'rb') as f:
    subset_pos = np.load(f)
positions = subset_pos[0]

In [ ]:
positions.shape

In [8]:
# Identify which indices (hybrid topology) are the water atoms that is being turned into an ion

# New topology indices
# Apo: [37532 37533 37534]
# Complex: [150820 150821 150822]

In [72]:
for k, v in htf._hybrid_to_new_map.items():
    if v in [150820, 150821, 150822]:
        print(k)

150811
150812
150813


In [75]:
for atom in htf.hybrid_topology.atoms:
    if atom.index in [150811, 150812, 150813]:
        print(atom)

HOH46139-O
HOH46139-H1
HOH46139-H2


In [73]:
htf.hybrid_topology.n_atoms

183508

# Write function for choosing indices to swap with

In [12]:
def choose_water_atoms(charge_diff, old_indices, hybrid_positions, hybrid_topology, radius=0.8):
    import mdtraj as md
    # Create trajectory
    traj = md.Trajectory(hybrid_positions, hybrid_topology)
    water_atoms = traj.topology.select(f"water")
    query_atoms = traj.top.select('protein')

    while True:
        # Get water atoms within radius of protein
        neighboring_atoms = md.compute_neighbors(traj, radius, query_atoms, haystack_indices=water_atoms)[0]

        # Get water atoms outside of radius of protein
        nonneighboring_residues = set([atom.residue.index for atom in traj.topology.atoms if (atom.index in water_atoms) and (atom.index not in neighboring_atoms)])
        assert len(nonneighboring_residues) > 0, "there are no available nonneighboring waters"
        # Choose N random nonneighboring waters, where N is determined based on the charge_diff
        choice_residues = np.random.choice(list(nonneighboring_residues), size=abs(charge_diff), replace=False)

        # Get the atom indices in the water(s)
        choice_indices = np.array([[atom.index for atom in traj.topology.residue(res).atoms] for res in choice_residues])
        
        if not np.array_equal(choice_indices, np.array(old_indices)):
            break
        
    return np.ndarray.flatten(choice_indices)


In [13]:
traj = md.Trajectory(htf.hybrid_positions, htf.hybrid_topology)
water_atoms = traj.topology.select(f"water")
query_atoms = traj.top.select('protein')

In [76]:
for atom in htf.hybrid_topology.atoms:
    print(atom.index, atom)

0 ACE332-H1
1 ACE332-CH3
2 ACE332-H2
3 ACE332-H3
4 ACE332-C
5 ACE332-O
6 THR333-N
7 THR333-H
8 THR333-CA
9 THR333-HA
10 THR333-CB
11 THR333-HB
12 THR333-CG2
13 THR333-HG21
14 THR333-HG22
15 THR333-HG23
16 THR333-OG1
17 THR333-HG1
18 THR333-C
19 THR333-O
20 ASN334-N
21 ASN334-H
22 ASN334-CA
23 ASN334-HA
24 ASN334-CB
25 ASN334-HB2
26 ASN334-HB3
27 ASN334-CG
28 ASN334-OD1
29 ASN334-ND2
30 ASN334-HD21
31 ASN334-HD22
32 ASN334-C
33 ASN334-O
34 LEU335-N
35 LEU335-H
36 LEU335-CA
37 LEU335-HA
38 LEU335-CB
39 LEU335-HB2
40 LEU335-HB3
41 LEU335-CG
42 LEU335-HG
43 LEU335-CD1
44 LEU335-HD11
45 LEU335-HD12
46 LEU335-HD13
47 LEU335-CD2
48 LEU335-HD21
49 LEU335-HD22
50 LEU335-HD23
51 LEU335-C
52 LEU335-O
53 CYS336-N
54 CYS336-H
55 CYS336-CA
56 CYS336-HA
57 CYS336-CB
58 CYS336-HB2
59 CYS336-HB3
60 CYS336-SG
61 CYS336-C
62 CYS336-O
63 PRO337-N
64 PRO337-CD
65 PRO337-HD2
66 PRO337-HD3
67 PRO337-CG
68 PRO337-HG2
69 PRO337-HG3
70 PRO337-CB
71 PRO337-HB2
72 PRO337-HB3
73 PRO337-CA
74 PRO337-HA
75 PRO337-C


1604 TRP436-HE3
1605 TRP436-CD2
1606 TRP436-C
1607 TRP436-O
1608 ASN437-N
1609 ASN437-H
1610 ASN437-CA
1611 ASN437-HA
1612 ASN437-CB
1613 ASN437-HB2
1614 ASN437-HB3
1615 ASN437-CG
1616 ASN437-OD1
1617 ASN437-ND2
1618 ASN437-HD21
1619 ASN437-HD22
1620 ASN437-C
1621 ASN437-O
1622 SER438-N
1623 SER438-H
1624 SER438-CA
1625 SER438-HA
1626 SER438-CB
1627 SER438-HB2
1628 SER438-HB3
1629 SER438-OG
1630 SER438-HG
1631 SER438-C
1632 SER438-O
1633 ASN439-N
1634 ASN439-H
1635 ASN439-CA
1636 ASN439-HA
1637 ASN439-CB
1638 ASN439-HB2
1639 ASN439-HB3
1640 ASN439-CG
1641 ASN439-OD1
1642 ASN439-ND2
1643 ASN439-HD21
1644 ASN439-HD22
1645 ASN439-C
1646 ASN439-O
1647 ASN440-N
1648 ASN440-H
1649 ASN440-CA
1650 ASN440-HA
1651 ASN440-CB
1652 ASN440-HB2
1653 ASN440-HB3
1654 ASN440-CG
1655 ASN440-OD1
1656 ASN440-ND2
1657 ASN440-HD21
1658 ASN440-HD22
1659 ASN440-C
1660 ASN440-O
1661 LEU441-N
1662 LEU441-H
1663 LEU441-CA
1664 LEU441-HA
1665 LEU441-CB
1666 LEU441-HB2
1667 LEU441-HB3
1668 LEU441-CG
1669 LEU441-HG


3339 HOH309-H2
3340 HOH310-O
3341 HOH310-H1
3342 HOH310-H2
3343 HOH311-O
3344 HOH311-H1
3345 HOH311-H2
3346 HOH312-O
3347 HOH312-H1
3348 HOH312-H2
3349 HOH313-O
3350 HOH313-H1
3351 HOH313-H2
3352 HOH314-O
3353 HOH314-H1
3354 HOH314-H2
3355 HOH315-O
3356 HOH315-H1
3357 HOH315-H2
3358 HOH316-O
3359 HOH316-H1
3360 HOH316-H2
3361 HOH317-O
3362 HOH317-H1
3363 HOH317-H2
3364 HOH318-O
3365 HOH318-H1
3366 HOH318-H2
3367 HOH319-O
3368 HOH319-H1
3369 HOH319-H2
3370 HOH320-O
3371 HOH320-H1
3372 HOH320-H2
3373 HOH321-O
3374 HOH321-H1
3375 HOH321-H2
3376 HOH322-O
3377 HOH322-H1
3378 HOH322-H2
3379 HOH323-O
3380 HOH323-H1
3381 HOH323-H2
3382 HOH324-O
3383 HOH324-H1
3384 HOH324-H2
3385 HOH325-O
3386 HOH325-H1
3387 HOH325-H2
3388 HOH326-O
3389 HOH326-H1
3390 HOH326-H2
3391 HOH327-O
3392 HOH327-H1
3393 HOH327-H2
3394 HOH328-O
3395 HOH328-H1
3396 HOH328-H2
3397 HOH329-O
3398 HOH329-H1
3399 HOH329-H2
3400 HOH330-O
3401 HOH330-H1
3402 HOH330-H2
3403 HOH331-O
3404 HOH331-H1
3405 HOH331-H2
3406 HOH332-O
340

5089 HOH893-O
5090 HOH893-H1
5091 HOH893-H2
5092 HOH894-O
5093 HOH894-H1
5094 HOH894-H2
5095 HOH895-O
5096 HOH895-H1
5097 HOH895-H2
5098 HOH896-O
5099 HOH896-H1
5100 HOH896-H2
5101 HOH897-O
5102 HOH897-H1
5103 HOH897-H2
5104 HOH898-O
5105 HOH898-H1
5106 HOH898-H2
5107 HOH899-O
5108 HOH899-H1
5109 HOH899-H2
5110 HOH900-O
5111 HOH900-H1
5112 HOH900-H2
5113 HOH901-O
5114 HOH901-H1
5115 HOH901-H2
5116 HOH902-O
5117 HOH902-H1
5118 HOH902-H2
5119 HOH903-O
5120 HOH903-H1
5121 HOH903-H2
5122 HOH904-O
5123 HOH904-H1
5124 HOH904-H2
5125 HOH905-O
5126 HOH905-H1
5127 HOH905-H2
5128 HOH906-O
5129 HOH906-H1
5130 HOH906-H2
5131 HOH907-O
5132 HOH907-H1
5133 HOH907-H2
5134 HOH908-O
5135 HOH908-H1
5136 HOH908-H2
5137 HOH909-O
5138 HOH909-H1
5139 HOH909-H2
5140 HOH910-O
5141 HOH910-H1
5142 HOH910-H2
5143 HOH911-O
5144 HOH911-H1
5145 HOH911-H2
5146 HOH912-O
5147 HOH912-H1
5148 HOH912-H2
5149 HOH913-O
5150 HOH913-H1
5151 HOH913-H2
5152 HOH914-O
5153 HOH914-H1
5154 HOH914-H2
5155 HOH915-O
5156 HOH915-H1
515

6838 HOH1476-O
6839 HOH1476-H1
6840 HOH1476-H2
6841 HOH1477-O
6842 HOH1477-H1
6843 HOH1477-H2
6844 HOH1478-O
6845 HOH1478-H1
6846 HOH1478-H2
6847 HOH1479-O
6848 HOH1479-H1
6849 HOH1479-H2
6850 HOH1480-O
6851 HOH1480-H1
6852 HOH1480-H2
6853 HOH1481-O
6854 HOH1481-H1
6855 HOH1481-H2
6856 HOH1482-O
6857 HOH1482-H1
6858 HOH1482-H2
6859 HOH1483-O
6860 HOH1483-H1
6861 HOH1483-H2
6862 HOH1484-O
6863 HOH1484-H1
6864 HOH1484-H2
6865 HOH1485-O
6866 HOH1485-H1
6867 HOH1485-H2
6868 HOH1486-O
6869 HOH1486-H1
6870 HOH1486-H2
6871 HOH1487-O
6872 HOH1487-H1
6873 HOH1487-H2
6874 HOH1488-O
6875 HOH1488-H1
6876 HOH1488-H2
6877 HOH1489-O
6878 HOH1489-H1
6879 HOH1489-H2
6880 HOH1490-O
6881 HOH1490-H1
6882 HOH1490-H2
6883 HOH1491-O
6884 HOH1491-H1
6885 HOH1491-H2
6886 HOH1492-O
6887 HOH1492-H1
6888 HOH1492-H2
6889 HOH1493-O
6890 HOH1493-H1
6891 HOH1493-H2
6892 HOH1494-O
6893 HOH1494-H1
6894 HOH1494-H2
6895 HOH1495-O
6896 HOH1495-H1
6897 HOH1495-H2
6898 HOH1496-O
6899 HOH1496-H1
6900 HOH1496-H2
6901 HOH1497-

8588 HOH2059-H1
8589 HOH2059-H2
8590 HOH2060-O
8591 HOH2060-H1
8592 HOH2060-H2
8593 HOH2061-O
8594 HOH2061-H1
8595 HOH2061-H2
8596 HOH2062-O
8597 HOH2062-H1
8598 HOH2062-H2
8599 HOH2063-O
8600 HOH2063-H1
8601 HOH2063-H2
8602 HOH2064-O
8603 HOH2064-H1
8604 HOH2064-H2
8605 HOH2065-O
8606 HOH2065-H1
8607 HOH2065-H2
8608 HOH2066-O
8609 HOH2066-H1
8610 HOH2066-H2
8611 HOH2067-O
8612 HOH2067-H1
8613 HOH2067-H2
8614 HOH2068-O
8615 HOH2068-H1
8616 HOH2068-H2
8617 HOH2069-O
8618 HOH2069-H1
8619 HOH2069-H2
8620 HOH2070-O
8621 HOH2070-H1
8622 HOH2070-H2
8623 HOH2071-O
8624 HOH2071-H1
8625 HOH2071-H2
8626 HOH2072-O
8627 HOH2072-H1
8628 HOH2072-H2
8629 HOH2073-O
8630 HOH2073-H1
8631 HOH2073-H2
8632 HOH2074-O
8633 HOH2074-H1
8634 HOH2074-H2
8635 HOH2075-O
8636 HOH2075-H1
8637 HOH2075-H2
8638 HOH2076-O
8639 HOH2076-H1
8640 HOH2076-H2
8641 HOH2077-O
8642 HOH2077-H1
8643 HOH2077-H2
8644 HOH2078-O
8645 HOH2078-H1
8646 HOH2078-H2
8647 HOH2079-O
8648 HOH2079-H1
8649 HOH2079-H2
8650 HOH2080-O
8651 HOH2080-

10088 HOH2559-H1
10089 HOH2559-H2
10090 HOH2560-O
10091 HOH2560-H1
10092 HOH2560-H2
10093 HOH2561-O
10094 HOH2561-H1
10095 HOH2561-H2
10096 HOH2562-O
10097 HOH2562-H1
10098 HOH2562-H2
10099 HOH2563-O
10100 HOH2563-H1
10101 HOH2563-H2
10102 HOH2564-O
10103 HOH2564-H1
10104 HOH2564-H2
10105 HOH2565-O
10106 HOH2565-H1
10107 HOH2565-H2
10108 HOH2566-O
10109 HOH2566-H1
10110 HOH2566-H2
10111 HOH2567-O
10112 HOH2567-H1
10113 HOH2567-H2
10114 HOH2568-O
10115 HOH2568-H1
10116 HOH2568-H2
10117 HOH2569-O
10118 HOH2569-H1
10119 HOH2569-H2
10120 HOH2570-O
10121 HOH2570-H1
10122 HOH2570-H2
10123 HOH2571-O
10124 HOH2571-H1
10125 HOH2571-H2
10126 HOH2572-O
10127 HOH2572-H1
10128 HOH2572-H2
10129 HOH2573-O
10130 HOH2573-H1
10131 HOH2573-H2
10132 HOH2574-O
10133 HOH2574-H1
10134 HOH2574-H2
10135 HOH2575-O
10136 HOH2575-H1
10137 HOH2575-H2
10138 HOH2576-O
10139 HOH2576-H1
10140 HOH2576-H2
10141 HOH2577-O
10142 HOH2577-H1
10143 HOH2577-H2
10144 HOH2578-O
10145 HOH2578-H1
10146 HOH2578-H2
10147 HOH2579-O


11838 HOH3142-H2
11839 HOH3143-O
11840 HOH3143-H1
11841 HOH3143-H2
11842 HOH3144-O
11843 HOH3144-H1
11844 HOH3144-H2
11845 HOH3145-O
11846 HOH3145-H1
11847 HOH3145-H2
11848 HOH3146-O
11849 HOH3146-H1
11850 HOH3146-H2
11851 HOH3147-O
11852 HOH3147-H1
11853 HOH3147-H2
11854 HOH3148-O
11855 HOH3148-H1
11856 HOH3148-H2
11857 HOH3149-O
11858 HOH3149-H1
11859 HOH3149-H2
11860 HOH3150-O
11861 HOH3150-H1
11862 HOH3150-H2
11863 HOH3151-O
11864 HOH3151-H1
11865 HOH3151-H2
11866 HOH3152-O
11867 HOH3152-H1
11868 HOH3152-H2
11869 HOH3153-O
11870 HOH3153-H1
11871 HOH3153-H2
11872 HOH3154-O
11873 HOH3154-H1
11874 HOH3154-H2
11875 HOH3155-O
11876 HOH3155-H1
11877 HOH3155-H2
11878 HOH3156-O
11879 HOH3156-H1
11880 HOH3156-H2
11881 HOH3157-O
11882 HOH3157-H1
11883 HOH3157-H2
11884 HOH3158-O
11885 HOH3158-H1
11886 HOH3158-H2
11887 HOH3159-O
11888 HOH3159-H1
11889 HOH3159-H2
11890 HOH3160-O
11891 HOH3160-H1
11892 HOH3160-H2
11893 HOH3161-O
11894 HOH3161-H1
11895 HOH3161-H2
11896 HOH3162-O
11897 HOH3162-H1


13587 HOH3725-H2
13588 HOH3726-O
13589 HOH3726-H1
13590 HOH3726-H2
13591 HOH3727-O
13592 HOH3727-H1
13593 HOH3727-H2
13594 HOH3728-O
13595 HOH3728-H1
13596 HOH3728-H2
13597 HOH3729-O
13598 HOH3729-H1
13599 HOH3729-H2
13600 HOH3730-O
13601 HOH3730-H1
13602 HOH3730-H2
13603 HOH3731-O
13604 HOH3731-H1
13605 HOH3731-H2
13606 HOH3732-O
13607 HOH3732-H1
13608 HOH3732-H2
13609 HOH3733-O
13610 HOH3733-H1
13611 HOH3733-H2
13612 HOH3734-O
13613 HOH3734-H1
13614 HOH3734-H2
13615 HOH3735-O
13616 HOH3735-H1
13617 HOH3735-H2
13618 HOH3736-O
13619 HOH3736-H1
13620 HOH3736-H2
13621 HOH3737-O
13622 HOH3737-H1
13623 HOH3737-H2
13624 HOH3738-O
13625 HOH3738-H1
13626 HOH3738-H2
13627 HOH3739-O
13628 HOH3739-H1
13629 HOH3739-H2
13630 HOH3740-O
13631 HOH3740-H1
13632 HOH3740-H2
13633 HOH3741-O
13634 HOH3741-H1
13635 HOH3741-H2
13636 HOH3742-O
13637 HOH3742-H1
13638 HOH3742-H2
13639 HOH3743-O
13640 HOH3743-H1
13641 HOH3743-H2
13642 HOH3744-O
13643 HOH3744-H1
13644 HOH3744-H2
13645 HOH3745-O
13646 HOH3745-H1


15087 HOH4225-H2
15088 HOH4226-O
15089 HOH4226-H1
15090 HOH4226-H2
15091 HOH4227-O
15092 HOH4227-H1
15093 HOH4227-H2
15094 HOH4228-O
15095 HOH4228-H1
15096 HOH4228-H2
15097 HOH4229-O
15098 HOH4229-H1
15099 HOH4229-H2
15100 HOH4230-O
15101 HOH4230-H1
15102 HOH4230-H2
15103 HOH4231-O
15104 HOH4231-H1
15105 HOH4231-H2
15106 HOH4232-O
15107 HOH4232-H1
15108 HOH4232-H2
15109 HOH4233-O
15110 HOH4233-H1
15111 HOH4233-H2
15112 HOH4234-O
15113 HOH4234-H1
15114 HOH4234-H2
15115 HOH4235-O
15116 HOH4235-H1
15117 HOH4235-H2
15118 HOH4236-O
15119 HOH4236-H1
15120 HOH4236-H2
15121 HOH4237-O
15122 HOH4237-H1
15123 HOH4237-H2
15124 HOH4238-O
15125 HOH4238-H1
15126 HOH4238-H2
15127 HOH4239-O
15128 HOH4239-H1
15129 HOH4239-H2
15130 HOH4240-O
15131 HOH4240-H1
15132 HOH4240-H2
15133 HOH4241-O
15134 HOH4241-H1
15135 HOH4241-H2
15136 HOH4242-O
15137 HOH4242-H1
15138 HOH4242-H2
15139 HOH4243-O
15140 HOH4243-H1
15141 HOH4243-H2
15142 HOH4244-O
15143 HOH4244-H1
15144 HOH4244-H2
15145 HOH4245-O
15146 HOH4245-H1


16837 HOH4809-O
16838 HOH4809-H1
16839 HOH4809-H2
16840 HOH4810-O
16841 HOH4810-H1
16842 HOH4810-H2
16843 HOH4811-O
16844 HOH4811-H1
16845 HOH4811-H2
16846 HOH4812-O
16847 HOH4812-H1
16848 HOH4812-H2
16849 HOH4813-O
16850 HOH4813-H1
16851 HOH4813-H2
16852 HOH4814-O
16853 HOH4814-H1
16854 HOH4814-H2
16855 HOH4815-O
16856 HOH4815-H1
16857 HOH4815-H2
16858 HOH4816-O
16859 HOH4816-H1
16860 HOH4816-H2
16861 HOH4817-O
16862 HOH4817-H1
16863 HOH4817-H2
16864 HOH4818-O
16865 HOH4818-H1
16866 HOH4818-H2
16867 HOH4819-O
16868 HOH4819-H1
16869 HOH4819-H2
16870 HOH4820-O
16871 HOH4820-H1
16872 HOH4820-H2
16873 HOH4821-O
16874 HOH4821-H1
16875 HOH4821-H2
16876 HOH4822-O
16877 HOH4822-H1
16878 HOH4822-H2
16879 HOH4823-O
16880 HOH4823-H1
16881 HOH4823-H2
16882 HOH4824-O
16883 HOH4824-H1
16884 HOH4824-H2
16885 HOH4825-O
16886 HOH4825-H1
16887 HOH4825-H2
16888 HOH4826-O
16889 HOH4826-H1
16890 HOH4826-H2
16891 HOH4827-O
16892 HOH4827-H1
16893 HOH4827-H2
16894 HOH4828-O
16895 HOH4828-H1
16896 HOH4828-H2


18587 HOH5392-H1
18588 HOH5392-H2
18589 HOH5393-O
18590 HOH5393-H1
18591 HOH5393-H2
18592 HOH5394-O
18593 HOH5394-H1
18594 HOH5394-H2
18595 HOH5395-O
18596 HOH5395-H1
18597 HOH5395-H2
18598 HOH5396-O
18599 HOH5396-H1
18600 HOH5396-H2
18601 HOH5397-O
18602 HOH5397-H1
18603 HOH5397-H2
18604 HOH5398-O
18605 HOH5398-H1
18606 HOH5398-H2
18607 HOH5399-O
18608 HOH5399-H1
18609 HOH5399-H2
18610 HOH5400-O
18611 HOH5400-H1
18612 HOH5400-H2
18613 HOH5401-O
18614 HOH5401-H1
18615 HOH5401-H2
18616 HOH5402-O
18617 HOH5402-H1
18618 HOH5402-H2
18619 HOH5403-O
18620 HOH5403-H1
18621 HOH5403-H2
18622 HOH5404-O
18623 HOH5404-H1
18624 HOH5404-H2
18625 HOH5405-O
18626 HOH5405-H1
18627 HOH5405-H2
18628 HOH5406-O
18629 HOH5406-H1
18630 HOH5406-H2
18631 HOH5407-O
18632 HOH5407-H1
18633 HOH5407-H2
18634 HOH5408-O
18635 HOH5408-H1
18636 HOH5408-H2
18637 HOH5409-O
18638 HOH5409-H1
18639 HOH5409-H2
18640 HOH5410-O
18641 HOH5410-H1
18642 HOH5410-H2
18643 HOH5411-O
18644 HOH5411-H1
18645 HOH5411-H2
18646 HOH5412-O


20336 HOH5975-H1
20337 HOH5975-H2
20338 HOH5976-O
20339 HOH5976-H1
20340 HOH5976-H2
20341 HOH5977-O
20342 HOH5977-H1
20343 HOH5977-H2
20344 HOH5978-O
20345 HOH5978-H1
20346 HOH5978-H2
20347 HOH5979-O
20348 HOH5979-H1
20349 HOH5979-H2
20350 HOH5980-O
20351 HOH5980-H1
20352 HOH5980-H2
20353 HOH5981-O
20354 HOH5981-H1
20355 HOH5981-H2
20356 HOH5982-O
20357 HOH5982-H1
20358 HOH5982-H2
20359 HOH5983-O
20360 HOH5983-H1
20361 HOH5983-H2
20362 HOH5984-O
20363 HOH5984-H1
20364 HOH5984-H2
20365 HOH5985-O
20366 HOH5985-H1
20367 HOH5985-H2
20368 HOH5986-O
20369 HOH5986-H1
20370 HOH5986-H2
20371 HOH5987-O
20372 HOH5987-H1
20373 HOH5987-H2
20374 HOH5988-O
20375 HOH5988-H1
20376 HOH5988-H2
20377 HOH5989-O
20378 HOH5989-H1
20379 HOH5989-H2
20380 HOH5990-O
20381 HOH5990-H1
20382 HOH5990-H2
20383 HOH5991-O
20384 HOH5991-H1
20385 HOH5991-H2
20386 HOH5992-O
20387 HOH5992-H1
20388 HOH5992-H2
20389 HOH5993-O
20390 HOH5993-H1
20391 HOH5993-H2
20392 HOH5994-O
20393 HOH5994-H1
20394 HOH5994-H2
20395 HOH5995-O


22086 HOH6558-H2
22087 HOH6559-O
22088 HOH6559-H1
22089 HOH6559-H2
22090 HOH6560-O
22091 HOH6560-H1
22092 HOH6560-H2
22093 HOH6561-O
22094 HOH6561-H1
22095 HOH6561-H2
22096 HOH6562-O
22097 HOH6562-H1
22098 HOH6562-H2
22099 HOH6563-O
22100 HOH6563-H1
22101 HOH6563-H2
22102 HOH6564-O
22103 HOH6564-H1
22104 HOH6564-H2
22105 HOH6565-O
22106 HOH6565-H1
22107 HOH6565-H2
22108 HOH6566-O
22109 HOH6566-H1
22110 HOH6566-H2
22111 HOH6567-O
22112 HOH6567-H1
22113 HOH6567-H2
22114 HOH6568-O
22115 HOH6568-H1
22116 HOH6568-H2
22117 HOH6569-O
22118 HOH6569-H1
22119 HOH6569-H2
22120 HOH6570-O
22121 HOH6570-H1
22122 HOH6570-H2
22123 HOH6571-O
22124 HOH6571-H1
22125 HOH6571-H2
22126 HOH6572-O
22127 HOH6572-H1
22128 HOH6572-H2
22129 HOH6573-O
22130 HOH6573-H1
22131 HOH6573-H2
22132 HOH6574-O
22133 HOH6574-H1
22134 HOH6574-H2
22135 HOH6575-O
22136 HOH6575-H1
22137 HOH6575-H2
22138 HOH6576-O
22139 HOH6576-H1
22140 HOH6576-H2
22141 HOH6577-O
22142 HOH6577-H1
22143 HOH6577-H2
22144 HOH6578-O
22145 HOH6578-H1


23586 HOH7058-H2
23587 HOH7059-O
23588 HOH7059-H1
23589 HOH7059-H2
23590 HOH7060-O
23591 HOH7060-H1
23592 HOH7060-H2
23593 HOH7061-O
23594 HOH7061-H1
23595 HOH7061-H2
23596 HOH7062-O
23597 HOH7062-H1
23598 HOH7062-H2
23599 HOH7063-O
23600 HOH7063-H1
23601 HOH7063-H2
23602 HOH7064-O
23603 HOH7064-H1
23604 HOH7064-H2
23605 HOH7065-O
23606 HOH7065-H1
23607 HOH7065-H2
23608 HOH7066-O
23609 HOH7066-H1
23610 HOH7066-H2
23611 HOH7067-O
23612 HOH7067-H1
23613 HOH7067-H2
23614 HOH7068-O
23615 HOH7068-H1
23616 HOH7068-H2
23617 HOH7069-O
23618 HOH7069-H1
23619 HOH7069-H2
23620 HOH7070-O
23621 HOH7070-H1
23622 HOH7070-H2
23623 HOH7071-O
23624 HOH7071-H1
23625 HOH7071-H2
23626 HOH7072-O
23627 HOH7072-H1
23628 HOH7072-H2
23629 HOH7073-O
23630 HOH7073-H1
23631 HOH7073-H2
23632 HOH7074-O
23633 HOH7074-H1
23634 HOH7074-H2
23635 HOH7075-O
23636 HOH7075-H1
23637 HOH7075-H2
23638 HOH7076-O
23639 HOH7076-H1
23640 HOH7076-H2
23641 HOH7077-O
23642 HOH7077-H1
23643 HOH7077-H2
23644 HOH7078-O
23645 HOH7078-H1


25336 HOH7642-O
25337 HOH7642-H1
25338 HOH7642-H2
25339 HOH7643-O
25340 HOH7643-H1
25341 HOH7643-H2
25342 HOH7644-O
25343 HOH7644-H1
25344 HOH7644-H2
25345 HOH7645-O
25346 HOH7645-H1
25347 HOH7645-H2
25348 HOH7646-O
25349 HOH7646-H1
25350 HOH7646-H2
25351 HOH7647-O
25352 HOH7647-H1
25353 HOH7647-H2
25354 HOH7648-O
25355 HOH7648-H1
25356 HOH7648-H2
25357 HOH7649-O
25358 HOH7649-H1
25359 HOH7649-H2
25360 HOH7650-O
25361 HOH7650-H1
25362 HOH7650-H2
25363 HOH7651-O
25364 HOH7651-H1
25365 HOH7651-H2
25366 HOH7652-O
25367 HOH7652-H1
25368 HOH7652-H2
25369 HOH7653-O
25370 HOH7653-H1
25371 HOH7653-H2
25372 HOH7654-O
25373 HOH7654-H1
25374 HOH7654-H2
25375 HOH7655-O
25376 HOH7655-H1
25377 HOH7655-H2
25378 HOH7656-O
25379 HOH7656-H1
25380 HOH7656-H2
25381 HOH7657-O
25382 HOH7657-H1
25383 HOH7657-H2
25384 HOH7658-O
25385 HOH7658-H1
25386 HOH7658-H2
25387 HOH7659-O
25388 HOH7659-H1
25389 HOH7659-H2
25390 HOH7660-O
25391 HOH7660-H1
25392 HOH7660-H2
25393 HOH7661-O
25394 HOH7661-H1
25395 HOH7661-H2


27085 HOH8225-O
27086 HOH8225-H1
27087 HOH8225-H2
27088 HOH8226-O
27089 HOH8226-H1
27090 HOH8226-H2
27091 HOH8227-O
27092 HOH8227-H1
27093 HOH8227-H2
27094 HOH8228-O
27095 HOH8228-H1
27096 HOH8228-H2
27097 HOH8229-O
27098 HOH8229-H1
27099 HOH8229-H2
27100 HOH8230-O
27101 HOH8230-H1
27102 HOH8230-H2
27103 HOH8231-O
27104 HOH8231-H1
27105 HOH8231-H2
27106 HOH8232-O
27107 HOH8232-H1
27108 HOH8232-H2
27109 HOH8233-O
27110 HOH8233-H1
27111 HOH8233-H2
27112 HOH8234-O
27113 HOH8234-H1
27114 HOH8234-H2
27115 HOH8235-O
27116 HOH8235-H1
27117 HOH8235-H2
27118 HOH8236-O
27119 HOH8236-H1
27120 HOH8236-H2
27121 HOH8237-O
27122 HOH8237-H1
27123 HOH8237-H2
27124 HOH8238-O
27125 HOH8238-H1
27126 HOH8238-H2
27127 HOH8239-O
27128 HOH8239-H1
27129 HOH8239-H2
27130 HOH8240-O
27131 HOH8240-H1
27132 HOH8240-H2
27133 HOH8241-O
27134 HOH8241-H1
27135 HOH8241-H2
27136 HOH8242-O
27137 HOH8242-H1
27138 HOH8242-H2
27139 HOH8243-O
27140 HOH8243-H1
27141 HOH8243-H2
27142 HOH8244-O
27143 HOH8244-H1
27144 HOH8244-H2


28835 HOH8808-H1
28836 HOH8808-H2
28837 HOH8809-O
28838 HOH8809-H1
28839 HOH8809-H2
28840 HOH8810-O
28841 HOH8810-H1
28842 HOH8810-H2
28843 HOH8811-O
28844 HOH8811-H1
28845 HOH8811-H2
28846 HOH8812-O
28847 HOH8812-H1
28848 HOH8812-H2
28849 HOH8813-O
28850 HOH8813-H1
28851 HOH8813-H2
28852 HOH8814-O
28853 HOH8814-H1
28854 HOH8814-H2
28855 HOH8815-O
28856 HOH8815-H1
28857 HOH8815-H2
28858 HOH8816-O
28859 HOH8816-H1
28860 HOH8816-H2
28861 HOH8817-O
28862 HOH8817-H1
28863 HOH8817-H2
28864 HOH8818-O
28865 HOH8818-H1
28866 HOH8818-H2
28867 HOH8819-O
28868 HOH8819-H1
28869 HOH8819-H2
28870 HOH8820-O
28871 HOH8820-H1
28872 HOH8820-H2
28873 HOH8821-O
28874 HOH8821-H1
28875 HOH8821-H2
28876 HOH8822-O
28877 HOH8822-H1
28878 HOH8822-H2
28879 HOH8823-O
28880 HOH8823-H1
28881 HOH8823-H2
28882 HOH8824-O
28883 HOH8824-H1
28884 HOH8824-H2
28885 HOH8825-O
28886 HOH8825-H1
28887 HOH8825-H2
28888 HOH8826-O
28889 HOH8826-H1
28890 HOH8826-H2
28891 HOH8827-O
28892 HOH8827-H1
28893 HOH8827-H2
28894 HOH8828-O


30585 HOH9391-H2
30586 HOH9392-O
30587 HOH9392-H1
30588 HOH9392-H2
30589 HOH9393-O
30590 HOH9393-H1
30591 HOH9393-H2
30592 HOH9394-O
30593 HOH9394-H1
30594 HOH9394-H2
30595 HOH9395-O
30596 HOH9395-H1
30597 HOH9395-H2
30598 HOH9396-O
30599 HOH9396-H1
30600 HOH9396-H2
30601 HOH9397-O
30602 HOH9397-H1
30603 HOH9397-H2
30604 HOH9398-O
30605 HOH9398-H1
30606 HOH9398-H2
30607 HOH9399-O
30608 HOH9399-H1
30609 HOH9399-H2
30610 HOH9400-O
30611 HOH9400-H1
30612 HOH9400-H2
30613 HOH9401-O
30614 HOH9401-H1
30615 HOH9401-H2
30616 HOH9402-O
30617 HOH9402-H1
30618 HOH9402-H2
30619 HOH9403-O
30620 HOH9403-H1
30621 HOH9403-H2
30622 HOH9404-O
30623 HOH9404-H1
30624 HOH9404-H2
30625 HOH9405-O
30626 HOH9405-H1
30627 HOH9405-H2
30628 HOH9406-O
30629 HOH9406-H1
30630 HOH9406-H2
30631 HOH9407-O
30632 HOH9407-H1
30633 HOH9407-H2
30634 HOH9408-O
30635 HOH9408-H1
30636 HOH9408-H2
30637 HOH9409-O
30638 HOH9409-H1
30639 HOH9409-H2
30640 HOH9410-O
30641 HOH9410-H1
30642 HOH9410-H2
30643 HOH9411-O
30644 HOH9411-H1


32085 HOH9891-H2
32086 HOH9892-O
32087 HOH9892-H1
32088 HOH9892-H2
32089 HOH9893-O
32090 HOH9893-H1
32091 HOH9893-H2
32092 HOH9894-O
32093 HOH9894-H1
32094 HOH9894-H2
32095 HOH9895-O
32096 HOH9895-H1
32097 HOH9895-H2
32098 HOH9896-O
32099 HOH9896-H1
32100 HOH9896-H2
32101 HOH9897-O
32102 HOH9897-H1
32103 HOH9897-H2
32104 HOH9898-O
32105 HOH9898-H1
32106 HOH9898-H2
32107 HOH9899-O
32108 HOH9899-H1
32109 HOH9899-H2
32110 HOH9900-O
32111 HOH9900-H1
32112 HOH9900-H2
32113 HOH9901-O
32114 HOH9901-H1
32115 HOH9901-H2
32116 HOH9902-O
32117 HOH9902-H1
32118 HOH9902-H2
32119 HOH9903-O
32120 HOH9903-H1
32121 HOH9903-H2
32122 HOH9904-O
32123 HOH9904-H1
32124 HOH9904-H2
32125 HOH9905-O
32126 HOH9905-H1
32127 HOH9905-H2
32128 HOH9906-O
32129 HOH9906-H1
32130 HOH9906-H2
32131 HOH9907-O
32132 HOH9907-H1
32133 HOH9907-H2
32134 HOH9908-O
32135 HOH9908-H1
32136 HOH9908-H2
32137 HOH9909-O
32138 HOH9909-H1
32139 HOH9909-H2
32140 HOH9910-O
32141 HOH9910-H1
32142 HOH9910-H2
32143 HOH9911-O
32144 HOH9911-H1


33834 HOH10474-H2
33835 HOH10475-O
33836 HOH10475-H1
33837 HOH10475-H2
33838 HOH10476-O
33839 HOH10476-H1
33840 HOH10476-H2
33841 HOH10477-O
33842 HOH10477-H1
33843 HOH10477-H2
33844 HOH10478-O
33845 HOH10478-H1
33846 HOH10478-H2
33847 HOH10479-O
33848 HOH10479-H1
33849 HOH10479-H2
33850 HOH10480-O
33851 HOH10480-H1
33852 HOH10480-H2
33853 HOH10481-O
33854 HOH10481-H1
33855 HOH10481-H2
33856 HOH10482-O
33857 HOH10482-H1
33858 HOH10482-H2
33859 HOH10483-O
33860 HOH10483-H1
33861 HOH10483-H2
33862 HOH10484-O
33863 HOH10484-H1
33864 HOH10484-H2
33865 HOH10485-O
33866 HOH10485-H1
33867 HOH10485-H2
33868 HOH10486-O
33869 HOH10486-H1
33870 HOH10486-H2
33871 HOH10487-O
33872 HOH10487-H1
33873 HOH10487-H2
33874 HOH10488-O
33875 HOH10488-H1
33876 HOH10488-H2
33877 HOH10489-O
33878 HOH10489-H1
33879 HOH10489-H2
33880 HOH10490-O
33881 HOH10490-H1
33882 HOH10490-H2
33883 HOH10491-O
33884 HOH10491-H1
33885 HOH10491-H2
33886 HOH10492-O
33887 HOH10492-H1
33888 HOH10492-H2
33889 HOH10493-O
33890 HOH10

35334 HOH10974-H2
35335 HOH10975-O
35336 HOH10975-H1
35337 HOH10975-H2
35338 HOH10976-O
35339 HOH10976-H1
35340 HOH10976-H2
35341 HOH10977-O
35342 HOH10977-H1
35343 HOH10977-H2
35344 HOH10978-O
35345 HOH10978-H1
35346 HOH10978-H2
35347 HOH10979-O
35348 HOH10979-H1
35349 HOH10979-H2
35350 HOH10980-O
35351 HOH10980-H1
35352 HOH10980-H2
35353 HOH10981-O
35354 HOH10981-H1
35355 HOH10981-H2
35356 HOH10982-O
35357 HOH10982-H1
35358 HOH10982-H2
35359 HOH10983-O
35360 HOH10983-H1
35361 HOH10983-H2
35362 HOH10984-O
35363 HOH10984-H1
35364 HOH10984-H2
35365 HOH10985-O
35366 HOH10985-H1
35367 HOH10985-H2
35368 HOH10986-O
35369 HOH10986-H1
35370 HOH10986-H2
35371 HOH10987-O
35372 HOH10987-H1
35373 HOH10987-H2
35374 HOH10988-O
35375 HOH10988-H1
35376 HOH10988-H2
35377 HOH10989-O
35378 HOH10989-H1
35379 HOH10989-H2
35380 HOH10990-O
35381 HOH10990-H1
35382 HOH10990-H2
35383 HOH10991-O
35384 HOH10991-H1
35385 HOH10991-H2
35386 HOH10992-O
35387 HOH10992-H1
35388 HOH10992-H2
35389 HOH10993-O
35390 HOH10

37084 HOH11558-O
37085 HOH11558-H1
37086 HOH11558-H2
37087 HOH11559-O
37088 HOH11559-H1
37089 HOH11559-H2
37090 HOH11560-O
37091 HOH11560-H1
37092 HOH11560-H2
37093 HOH11561-O
37094 HOH11561-H1
37095 HOH11561-H2
37096 HOH11562-O
37097 HOH11562-H1
37098 HOH11562-H2
37099 HOH11563-O
37100 HOH11563-H1
37101 HOH11563-H2
37102 HOH11564-O
37103 HOH11564-H1
37104 HOH11564-H2
37105 HOH11565-O
37106 HOH11565-H1
37107 HOH11565-H2
37108 HOH11566-O
37109 HOH11566-H1
37110 HOH11566-H2
37111 HOH11567-O
37112 HOH11567-H1
37113 HOH11567-H2
37114 HOH11568-O
37115 HOH11568-H1
37116 HOH11568-H2
37117 HOH11569-O
37118 HOH11569-H1
37119 HOH11569-H2
37120 HOH11570-O
37121 HOH11570-H1
37122 HOH11570-H2
37123 HOH11571-O
37124 HOH11571-H1
37125 HOH11571-H2
37126 HOH11572-O
37127 HOH11572-H1
37128 HOH11572-H2
37129 HOH11573-O
37130 HOH11573-H1
37131 HOH11573-H2
37132 HOH11574-O
37133 HOH11574-H1
37134 HOH11574-H2
37135 HOH11575-O
37136 HOH11575-H1
37137 HOH11575-H2
37138 HOH11576-O
37139 HOH11576-H1
37140 HOH11

38834 HOH12141-H1
38835 HOH12141-H2
38836 HOH12142-O
38837 HOH12142-H1
38838 HOH12142-H2
38839 HOH12143-O
38840 HOH12143-H1
38841 HOH12143-H2
38842 HOH12144-O
38843 HOH12144-H1
38844 HOH12144-H2
38845 HOH12145-O
38846 HOH12145-H1
38847 HOH12145-H2
38848 HOH12146-O
38849 HOH12146-H1
38850 HOH12146-H2
38851 HOH12147-O
38852 HOH12147-H1
38853 HOH12147-H2
38854 HOH12148-O
38855 HOH12148-H1
38856 HOH12148-H2
38857 HOH12149-O
38858 HOH12149-H1
38859 HOH12149-H2
38860 HOH12150-O
38861 HOH12150-H1
38862 HOH12150-H2
38863 HOH12151-O
38864 HOH12151-H1
38865 HOH12151-H2
38866 HOH12152-O
38867 HOH12152-H1
38868 HOH12152-H2
38869 HOH12153-O
38870 HOH12153-H1
38871 HOH12153-H2
38872 HOH12154-O
38873 HOH12154-H1
38874 HOH12154-H2
38875 HOH12155-O
38876 HOH12155-H1
38877 HOH12155-H2
38878 HOH12156-O
38879 HOH12156-H1
38880 HOH12156-H2
38881 HOH12157-O
38882 HOH12157-H1
38883 HOH12157-H2
38884 HOH12158-O
38885 HOH12158-H1
38886 HOH12158-H2
38887 HOH12159-O
38888 HOH12159-H1
38889 HOH12159-H2
38890 HOH1

40833 HOH12807-H2
40834 HOH12808-O
40835 HOH12808-H1
40836 HOH12808-H2
40837 HOH12809-O
40838 HOH12809-H1
40839 HOH12809-H2
40840 HOH12810-O
40841 HOH12810-H1
40842 HOH12810-H2
40843 HOH12811-O
40844 HOH12811-H1
40845 HOH12811-H2
40846 HOH12812-O
40847 HOH12812-H1
40848 HOH12812-H2
40849 HOH12813-O
40850 HOH12813-H1
40851 HOH12813-H2
40852 HOH12814-O
40853 HOH12814-H1
40854 HOH12814-H2
40855 HOH12815-O
40856 HOH12815-H1
40857 HOH12815-H2
40858 HOH12816-O
40859 HOH12816-H1
40860 HOH12816-H2
40861 HOH12817-O
40862 HOH12817-H1
40863 HOH12817-H2
40864 HOH12818-O
40865 HOH12818-H1
40866 HOH12818-H2
40867 HOH12819-O
40868 HOH12819-H1
40869 HOH12819-H2
40870 HOH12820-O
40871 HOH12820-H1
40872 HOH12820-H2
40873 HOH12821-O
40874 HOH12821-H1
40875 HOH12821-H2
40876 HOH12822-O
40877 HOH12822-H1
40878 HOH12822-H2
40879 HOH12823-O
40880 HOH12823-H1
40881 HOH12823-H2
40882 HOH12824-O
40883 HOH12824-H1
40884 HOH12824-H2
40885 HOH12825-O
40886 HOH12825-H1
40887 HOH12825-H2
40888 HOH12826-O
40889 HOH12

42833 HOH13474-H1
42834 HOH13474-H2
42835 HOH13475-O
42836 HOH13475-H1
42837 HOH13475-H2
42838 HOH13476-O
42839 HOH13476-H1
42840 HOH13476-H2
42841 HOH13477-O
42842 HOH13477-H1
42843 HOH13477-H2
42844 HOH13478-O
42845 HOH13478-H1
42846 HOH13478-H2
42847 HOH13479-O
42848 HOH13479-H1
42849 HOH13479-H2
42850 HOH13480-O
42851 HOH13480-H1
42852 HOH13480-H2
42853 HOH13481-O
42854 HOH13481-H1
42855 HOH13481-H2
42856 HOH13482-O
42857 HOH13482-H1
42858 HOH13482-H2
42859 HOH13483-O
42860 HOH13483-H1
42861 HOH13483-H2
42862 HOH13484-O
42863 HOH13484-H1
42864 HOH13484-H2
42865 HOH13485-O
42866 HOH13485-H1
42867 HOH13485-H2
42868 HOH13486-O
42869 HOH13486-H1
42870 HOH13486-H2
42871 HOH13487-O
42872 HOH13487-H1
42873 HOH13487-H2
42874 HOH13488-O
42875 HOH13488-H1
42876 HOH13488-H2
42877 HOH13489-O
42878 HOH13489-H1
42879 HOH13489-H2
42880 HOH13490-O
42881 HOH13490-H1
42882 HOH13490-H2
42883 HOH13491-O
42884 HOH13491-H1
42885 HOH13491-H2
42886 HOH13492-O
42887 HOH13492-H1
42888 HOH13492-H2
42889 HOH1

44583 HOH14057-H2
44584 HOH14058-O
44585 HOH14058-H1
44586 HOH14058-H2
44587 HOH14059-O
44588 HOH14059-H1
44589 HOH14059-H2
44590 HOH14060-O
44591 HOH14060-H1
44592 HOH14060-H2
44593 HOH14061-O
44594 HOH14061-H1
44595 HOH14061-H2
44596 HOH14062-O
44597 HOH14062-H1
44598 HOH14062-H2
44599 HOH14063-O
44600 HOH14063-H1
44601 HOH14063-H2
44602 HOH14064-O
44603 HOH14064-H1
44604 HOH14064-H2
44605 HOH14065-O
44606 HOH14065-H1
44607 HOH14065-H2
44608 HOH14066-O
44609 HOH14066-H1
44610 HOH14066-H2
44611 HOH14067-O
44612 HOH14067-H1
44613 HOH14067-H2
44614 HOH14068-O
44615 HOH14068-H1
44616 HOH14068-H2
44617 HOH14069-O
44618 HOH14069-H1
44619 HOH14069-H2
44620 HOH14070-O
44621 HOH14070-H1
44622 HOH14070-H2
44623 HOH14071-O
44624 HOH14071-H1
44625 HOH14071-H2
44626 HOH14072-O
44627 HOH14072-H1
44628 HOH14072-H2
44629 HOH14073-O
44630 HOH14073-H1
44631 HOH14073-H2
44632 HOH14074-O
44633 HOH14074-H1
44634 HOH14074-H2
44635 HOH14075-O
44636 HOH14075-H1
44637 HOH14075-H2
44638 HOH14076-O
44639 HOH14

In [74]:
for atom in query_atoms:
    print(atom)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [34]:
swap_indices = choose_water_atoms(-1, [150813, 150814, 150815], htf.hybrid_positions, htf.hybrid_topology)

In [47]:
swap_indices

array([97175, 97176, 97177])

In [61]:
for atom in htf.hybrid_topology.atoms:
    if atom.index in swap_indices:
        print(atom)

HOH28259-O
HOH28259-H1
HOH28259-H2


In [38]:
og_indices = [150813, 150814, 150815]

In [57]:
for og, swap in zip(og_indices, swap_indices):
    print(positions[og])
    print(positions[swap])
    temp = copy.copy(positions[og])
    positions[og] = positions[swap]
    print(temp)
    positions[swap] = temp

[2.75746489 5.9123044  4.71677208]
[11.61960793 12.97693539  6.68765688]
[2.75746489 5.9123044  4.71677208]
[2.71012211 5.77269173 4.7510767 ]
[11.64937782 12.88596725  6.68673801]
[2.71012211 5.77269173 4.7510767 ]
[2.11051607 5.40358973 4.27983475]
[11.69618893 13.02747536  6.66039324]
[2.11051607 5.40358973 4.27983475]


In [44]:
positions[150813]

array([11.61960793, 12.97693539,  6.68765688])

In [45]:
positions[150814]

array([11.64937782, 12.88596725,  6.68673801])

In [46]:
positions[150815]

array([11.69618893, 13.02747536,  6.66039324])

In [58]:
positions[97175]

array([2.75746489, 5.9123044 , 4.71677208])

In [59]:
positions[97176]

array([2.71012211, 5.77269173, 4.7510767 ])

In [60]:
positions[97177]

array([2.11051607, 5.40358973, 4.27983475])

# Get the water indices (to be turned into ion) for apo

In [41]:
with open("/data/chodera/zhangi/perses_benchmark/neq/15/104/104_apo.pickle", "rb") as f:
    htf = pickle.load(f)

In [59]:
# Read in lambda = 0 cache
with open(os.path.join("/data/chodera/zhangi/perses_benchmark/neq/15/104/", f"104_apo_asp_1ns_snapshots.npy"), 'rb') as f:
    subset_pos = np.load(f)
positions = subset_pos[0]

In [18]:
# Identify which indices (hybrid topology) are the water atoms that is being turned into an ion

# New topology indices
# Apo: [37532 37533 37534]
# Complex: [150820 150821 150822]

In [43]:
for k, v in htf._hybrid_to_new_map.items():
    if v in [37532, 37533, 37534]:
        print(k)

37523
37524
37525


In [45]:
for atom in htf.hybrid_topology.atoms:
    if atom.index in [37523, 37524, 37525]:
        print(atom)

HOH11705-O
HOH11705-H1
HOH11705-H2


In [47]:
htf.hybrid_topology.n_atoms

44744

In [48]:
swap_indices = choose_water_atoms(-1, [37523, 37524, 37525], htf.hybrid_positions, htf.hybrid_topology)

In [49]:
swap_indices

array([13403, 13404, 13405])

In [50]:
for atom in htf.hybrid_topology.atoms:
    if atom.index in swap_indices:
        print(atom)

HOH3665-O
HOH3665-H1
HOH3665-H2


In [60]:
og_indices = [37523, 37524, 37525]

In [61]:
for og, swap in zip(og_indices, swap_indices):
    print(positions[og])
    print(positions[swap])
    temp = copy.copy(positions[og])
    positions[og] = positions[swap]
    positions[swap] = temp

[1.27297604 6.23424006 3.09856224]
[8.02543449 1.14856029 1.17571199]
[1.20960546 6.30275393 3.07729387]
[7.94678164 1.13592839 1.22878313]
[1.21940422 6.15773773 3.11953354]
[8.0821352  1.20366669 1.22966194]


In [62]:
positions[37523]

array([8.02543449, 1.14856029, 1.17571199])

In [63]:
positions[37524]

array([7.94678164, 1.13592839, 1.22878313])

In [64]:
positions[37525]

array([8.0821352 , 1.20366669, 1.22966194])

In [65]:
positions[13403]

array([1.27297604, 6.23424006, 3.09856224])

In [66]:
positions[13404]

array([1.20960546, 6.30275393, 3.07729387])

In [67]:
positions[13405]

array([1.21940422, 6.15773773, 3.11953354])