In [4]:
import os
import pickle
import mdtraj as md
import numpy as np
import logging 
from tqdm import tqdm
from simtk import unit
from simtk.openmm import app
# Set up logger
_logger = logging.getLogger()
_logger.setLevel(logging.INFO)

## K27A (0.2 nm, 1200 K)

In [2]:
sim_dir = 56
aa = 'trp'
outdir = '/data/chodera/zhangi/perses_benchmark/neq/12/'


In [3]:
with open(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_lys_1ns_snapshots.npy", "rb") as f:
    pos = np.load(f)

In [4]:
with open(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_0.pickle", "rb") as f:
    htf = pickle.load(f)
    

In [5]:
pos_old = np.zeros(shape=(pos.shape[0], htf._topology_proposal.old_topology.getNumAtoms(), pos.shape[2]))
for i, p in enumerate(pos):
    pos_old[i] = htf.old_positions(p*unit.nanometers)
    

In [6]:
box_vectors = np.array([val.value_in_unit_system(unit.md_unit_system) for val in htf.hybrid_system.getDefaultPeriodicBoxVectors()])
htf._topology_proposal.old_topology.setPeriodicBoxVectors(box_vectors)
htf._topology_proposal.old_topology.getPeriodicBoxVectors()


In [9]:
# Write PDB file using openmm bc it will include box vectors
app.PDBFile.writeFile(htf._topology_proposal.old_topology, pos_old[0], open(os.path.join(outdir, "test.pdb"), 'w'))


In [10]:
# Load pdb into mdtraj
pdb = md.load(os.path.join(outdir, "test.pdb"))


In [11]:
pdb.unitcell_vectors


array([[[6.7997, 0.    , 0.    ],
        [0.    , 6.7997, 0.    ],
        [0.    , 0.    , 6.7997]]], dtype=float32)

In [12]:
traj = md.Trajectory(pos_old, md.Topology.from_openmm(htf._topology_proposal.old_topology))
# Set unit cell vectors in traj based on pdb vectors
traj.unitcell_vectors = np.repeat(pdb.unitcell_vectors, 100, axis=0)
traj.image_molecules()


In [15]:
traj.save(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_{aa}_1ns_snapshots.dcd")
traj[0].save(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_{aa}_1ns_snapshots.pdb")

## K27A (0.4 nm, 1600 K)

In [15]:
sim_dir = 79
aa = 'lys'
outdir = '/data/chodera/zhangi/perses_benchmark/neq/12/'


In [16]:
with open(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_lys_1ns_snapshots.npy", "rb") as f:
    pos = np.load(f)

In [17]:
with open(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_0.pickle", "rb") as f:
    htf = pickle.load(f)
    

In [18]:
pos_old = np.zeros(shape=(pos.shape[0], htf._topology_proposal.old_topology.getNumAtoms(), pos.shape[2]))
for i, p in enumerate(pos):
    pos_old[i] = htf.old_positions(p*unit.nanometers)
    

In [19]:
box_vectors = np.array([val.value_in_unit_system(unit.md_unit_system) for val in htf.hybrid_system.getDefaultPeriodicBoxVectors()])
htf._topology_proposal.old_topology.setPeriodicBoxVectors(box_vectors)
htf._topology_proposal.old_topology.getPeriodicBoxVectors()


Quantity(value=array([[6.7997, 0.    , 0.    ],
       [0.    , 6.7997, 0.    ],
       [0.    , 0.    , 6.7997]]), unit=nanometer)

In [20]:
# Write PDB file using openmm bc it will include box vectors
app.PDBFile.writeFile(htf._topology_proposal.old_topology, pos_old[0], open(os.path.join(outdir, "test.pdb"), 'w'))


In [21]:
# Load pdb into mdtraj
pdb = md.load(os.path.join(outdir, "test.pdb"))


In [22]:
pdb.unitcell_vectors


array([[[6.7997, 0.    , 0.    ],
        [0.    , 6.7997, 0.    ],
        [0.    , 0.    , 6.7997]]], dtype=float32)

In [23]:
traj = md.Trajectory(pos_old, md.Topology.from_openmm(htf._topology_proposal.old_topology))
# Set unit cell vectors in traj based on pdb vectors
traj.unitcell_vectors = np.repeat(pdb.unitcell_vectors, 100, axis=0)
traj.image_molecules()


<mdtraj.Trajectory with 100 frames, 29474 atoms, 8989 residues, and unitcells at 0x2b8d83203cd0>

In [24]:
traj.save(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_{aa}_1ns_snapshots.dcd")
traj[0].save(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_{aa}_1ns_snapshots.pdb")

## A27K (0.4 nm, 1600 K)

In [25]:
sim_dir = 80
aa = 'lys'
outdir = '/data/chodera/zhangi/perses_benchmark/neq/12/'


In [26]:
with open(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_lys_1ns_snapshots.npy", "rb") as f:
    pos = np.load(f)

In [27]:
with open(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_1.pickle", "rb") as f:
    htf = pickle.load(f)
    

In [28]:
pos_new = np.zeros(shape=(pos.shape[0], htf._topology_proposal.new_topology.getNumAtoms(), pos.shape[2]))
for i, p in enumerate(pos):
    pos_new[i] = htf.new_positions(p*unit.nanometers)
    

In [29]:
box_vectors = np.array([val.value_in_unit_system(unit.md_unit_system) for val in htf.hybrid_system.getDefaultPeriodicBoxVectors()])
htf._topology_proposal.new_topology.setPeriodicBoxVectors(box_vectors)
htf._topology_proposal.new_topology.getPeriodicBoxVectors()


Quantity(value=array([[6.7997, 0.    , 0.    ],
       [0.    , 6.7997, 0.    ],
       [0.    , 0.    , 6.7997]]), unit=nanometer)

In [31]:
# Write PDB file using openmm bc it will include box vectors
app.PDBFile.writeFile(htf._topology_proposal.new_topology, pos_new[0], open(os.path.join(outdir, "test.pdb"), 'w'))


In [32]:
# Load pdb into mdtraj
pdb = md.load(os.path.join(outdir, "test.pdb"))


In [33]:
pdb.unitcell_vectors


array([[[6.7997, 0.    , 0.    ],
        [0.    , 6.7997, 0.    ],
        [0.    , 0.    , 6.7997]]], dtype=float32)

In [39]:
traj = md.Trajectory(pos_new, md.Topology.from_openmm(htf._topology_proposal.new_topology))
# Set unit cell vectors in traj based on pdb vectors
traj.unitcell_vectors = np.repeat(pdb.unitcell_vectors, 100, axis=0)
traj.image_molecules()


<mdtraj.Trajectory with 100 frames, 29454 atoms, 8983 residues, and unitcells at 0x2b8d82587a50>

In [40]:
traj.save(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_{aa}_1ns_snapshots.dcd")
traj[0].save(f"/data/chodera/zhangi/perses_benchmark/neq/12/{sim_dir}/{sim_dir}_complex_{aa}_1ns_snapshots.pdb")

In [ ]:
# note after imaging, the solvent box seems like its missing a slice in 2 diff directions, 
# but this is not present when i save the traj before imaging