In [1]:
import mdtraj as md
import numpy as np
import pickle
import os
from tqdm import tqdm_notebook
from simtk.openmm import app
from simtk.openmm import unit
from openeye import oechem

In [67]:
outdir = "/data/chodera/zhangi/perses_benchmark/neq/21/48"
i = 48
phase = 'complex'
cycle = 0

In [68]:
htf = pickle.load(open(os.path.join(outdir, f"{i}_{phase}.pickle"), "rb"))

In [69]:
with open(os.path.join(outdir, f"{i}_{phase}_{cycle}_forward_neq_old.npy"), 'rb') as f:
    neq_old = np.load(f)

In [58]:
with open(os.path.join(outdir, f"{i}_{phase}_{cycle}_reverse_neq_old_water.npy"), 'rb') as f:
    neq_reverse_old = np.load(f)

In [59]:
neq_old.shape

(1, 33415, 3)

In [70]:
modeller = app.Modeller(htf._topology_proposal.old_topology, htf.old_positions(htf.hybrid_positions))
modeller.deleteWater()

In [71]:
old_top = md.Topology.from_openmm(modeller.topology)

In [72]:
traj = md.Trajectory(np.array(neq_old), old_top)
box_vectors = np.array([val.value_in_unit_system(unit.md_unit_system) for val in htf.hybrid_system.getDefaultPeriodicBoxVectors()])
vectors = np.array([box_vectors]) 
traj.unitcell_vectors = np.repeat(vectors, 100, axis=0)
traj = traj.image_molecules()
traj.save(os.path.join(outdir, f"{i}_{phase}_{cycle}_forward_neq_old.dcd"))

TypeError: unitcell_vectors must be the same length as the trajectory. you provided [[[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]

 [[7.0626 0.     0.    ]
  [0.     7.0626 0.    ]
  [0.     0.     7.0626]]]

In [73]:
traj[0].save(os.path.join(outdir, f"{i}_{phase}_{cycle}_forward_old.pdb"))

In [64]:
traj = md.Trajectory(np.array(neq_reverse_old), old_top)
box_vectors = np.array([val.value_in_unit_system(unit.md_unit_system) for val in htf.hybrid_system.getDefaultPeriodicBoxVectors()])
vectors = np.array([box_vectors]) 
traj.unitcell_vectors = np.repeat(vectors, 1, axis=0)
traj = traj.image_molecules()
traj.save(os.path.join(outdir, f"{i}_{phase}_{cycle}_reverse_neq_old.dcd"))

In [65]:
traj[-1].save(os.path.join(outdir, f"{i}_{phase}_{cycle}_old.pdb"))

In [66]:
traj.xyz = traj.xyz[::-1]
traj.save(os.path.join(outdir, f"{i}_{phase}_{cycle}_reverse_neq_old_reversed.dcd"))

In [46]:
with open(os.path.join(outdir, f"{i}_{phase}_{cycle}_forward_neq_new_water.npy"), 'rb') as f:
    neq_new = np.load(f)

In [47]:
with open(os.path.join(outdir, f"{i}_{phase}_{cycle}_reverse_neq_new_water.npy"), 'rb') as f:
    neq_reverse_new = np.load(f)

In [48]:
modeller = app.Modeller(htf._topology_proposal.new_topology, htf.new_positions(htf.hybrid_positions))
# modeller.deleteWater()

In [49]:
top = md.Topology.from_openmm(modeller.topology)

In [50]:
traj = md.Trajectory(np.array(neq_new), top)
traj.save(os.path.join(outdir, f"{i}_{phase}_{cycle}_forward_neq_new.dcd"))

In [51]:
traj[-1].save(os.path.join(outdir, f"{i}_{phase}_{cycle}_forward_new.pdb"))

In [52]:
traj = md.Trajectory(np.array(neq_reverse_new), top)
traj.save(os.path.join(outdir, f"{i}_{phase}_{cycle}_reverse_neq_new.dcd"))

In [53]:
traj[0].save(os.path.join(outdir, f"{i}_{phase}_{cycle}_new.pdb"))

In [54]:
traj = md.Trajectory(np.array(neq_reverse_new), top)
traj.xyz = traj.xyz[::-1]
traj.save(os.path.join(outdir, f"{i}_{phase}_{cycle}_reverse_neq_new_reversed.dcd"))